{ pkgs, config, ... }: {
  stylix = {
    enable = true;

    # Whether to enable targets by default.
    # When this is false, all targets are disabled unless explicitly enabled.
    autoEnable = true;

    # Whether to enable theming for packages via overlays.
    # Default : config.stylix.autoEnable
    overlays = config.stylix.autoEnable; # boolean

    # An override that will be applied to stylix.base16Scheme when generating config.lib.stylix.colors.
    # Takes anything that a scheme generated by base16nix can take as argument to override.
    override = {};

    # Whether to check that the Stylix release matches the releases of NixOS, Home Manager, and nix-darwin.
    # If this option is enabled and a mismatch is detected,
    # a warning will be printed when the user configuration is being built.    
    enableReleaseChecks = true;

    polarity = "dark"; # "either","dark","light"

    imageScalingMode = "fill"; # stretch, fill, fit, center, tile
    image = pkgs.fetchurl {
      url = "https://raw.githubusercontent.com/msalmanrafadhlih/Dotfiles/refs/heads/bspwm/home/Assets/Wallpaper/wallpaper8.jpeg";
      hash = "sha256-VZp1wy2N0GApt48ILRY+pIAhAjCt02GmqmxHRTWAEoA=";
    };

    ## A scheme following the base16 standard.
    ## Default : Automatically selected from the background image.
    ## The default will throw if config.stylix.image is null.
    ## This can be a path to a file, a string of YAML, or an attribute set.
    # base16Scheme = null;

    ########
    # Opacity Default = 1.0
    opacity = {
      # The opacity of the windows of applications,
      applications = 0.8;
      # The opacity of the windows of bars/widgets,
      desktop = 0.8;
      # The opacity of the windows of notifications/popups,
      popups = 0.8;
      # The opacity of the windows of terminals,
      terminal = 0.8;
    };

    ## Attributes defining the systemwide cursor.
    ## Set either all or none of these attributes.
    cursor = {
      name = null; # null or string
      package = null; # null or package
      size = null; # null or integer
      
    };

    ########## 
    ## Fonts Theming
    fonts = {
      # packages = []; # list of packages
      sizes = {
        applications = 12;
        desktop = 10;
        popups = config.stylix.fonts.sizes.desktop;
        terminal = config.stylix.fonts.sizes.applications;
      };
      
      emoji = {
        name = "Noto Color Emoji";
        package = pkgs.noto-fonts-color-emoji;
      };

      monospace = {
        name = "Dejavu Sans Mono";
        package = pkgs.dejavu_fonts;
      };

      sansSerif = {
        name = "DejaVu Sans";
        package = pkgs.dejavu_fonts;
      };

      serif = {
        name = "DejaVu Serif";
        package = pkgs.dejavu_fonts;
      };
    };
    
    #########
    # Icons Theming
    icons = {
      enable = false;
      dark = null; # null or string
      light = null;
      package = null; # null or package
    };


  };
    # Target Applications
  imports = [
    ./gtk.nix
  ];
}
